-- Campagnes Alpha Import Exchange (8 secteurs x preroll + bannière).
-- À exécuter dans Supabase → SQL Editor, APRÈS avoir téléversé les 16 images dans le bucket public `ad-media`, dossier `sectors/`.
-- Idempotent : relancer le script ne crée pas de doublons.

do $$
declare adv uuid;
begin
  select id into adv from public.advertisers where name = 'Alpha Import Exchange' limit 1;
  if adv is null then
    insert into public.advertisers (name, contact_name, contact_email, phone, status, notes)
    values ('Alpha Import Exchange', 'A.Onoseke House Investment RDC', 'contact@aonosekehouseinvestmentdrc.site', '+243 999 894 788', 'active',
            'Annonceur maison : importation sécurisée Chine, Turquie, Dubaï, Japon, Thaïlande vers la RDC')
    returning id into adv;
  end if;

  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Sourcing & Achats (preroll)', 'preroll', '{"title": "Achetez directement à la source", "subtitle": "Fournisseurs vérifiés en Chine, Turquie, Dubaï, Japon et Thaïlande.", "cta": "Demander un devis", "url": "https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-sourcing", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/sourcing-preroll.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Sourcing & Achats (preroll)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Sourcing & Achats (banner)', 'banner', '{"title": "Achetez directement à la source", "subtitle": "Fournisseurs vérifiés en Chine, Turquie, Dubaï, Japon et Thaïlande.", "cta": "Demander un devis", "url": "https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-sourcing", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/sourcing-banner.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Sourcing & Achats (banner)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Fret Maritime (preroll)', 'preroll', '{"title": "Vos conteneurs, de l''Asie à Kinshasa", "subtitle": "Un suivi complet, de l''embarquement à la livraison.", "cta": "Voir le circuit", "url": "https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-maritime", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/maritime-preroll.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Fret Maritime (preroll)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Fret Maritime (banner)', 'banner', '{"title": "Vos conteneurs, de l''Asie à Kinshasa", "subtitle": "Un suivi complet, de l''embarquement à la livraison.", "cta": "Voir le circuit", "url": "https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-maritime", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/maritime-banner.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Fret Maritime (banner)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Fret Aérien (preroll)', 'preroll', '{"title": "Urgent ? Livré par avion", "subtitle": "Des délais maîtrisés pour vos marchandises sensibles.", "cta": "Demander un devis", "url": "https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-aerien", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/aerien-preroll.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Fret Aérien (preroll)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Fret Aérien (banner)', 'banner', '{"title": "Urgent ? Livré par avion", "subtitle": "Des délais maîtrisés pour vos marchandises sensibles.", "cta": "Demander un devis", "url": "https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-aerien", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/aerien-banner.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Fret Aérien (banner)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Dédouanement Kinshasa (preroll)', 'preroll', '{"title": "La douane sans casse-tête", "subtitle": "Commissionnaires agréés, dossier complet, circuit maîtrisé.", "cta": "Comment ça marche", "url": "https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-douane", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/douane-preroll.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Dédouanement Kinshasa (preroll)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Dédouanement Kinshasa (banner)', 'banner', '{"title": "La douane sans casse-tête", "subtitle": "Commissionnaires agréés, dossier complet, circuit maîtrisé.", "cta": "Comment ça marche", "url": "https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-douane", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/douane-banner.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Dédouanement Kinshasa (banner)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Contrôle Qualité (preroll)', 'preroll', '{"title": "Vérifié avant de partir", "subtitle": "Inspection avant expédition et rapport photo.", "cta": "En savoir plus", "url": "https://aonosekehouseinvestmentdrc.site/services?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-qualite", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/qualite-preroll.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Contrôle Qualité (preroll)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Contrôle Qualité (banner)', 'banner', '{"title": "Vérifié avant de partir", "subtitle": "Inspection avant expédition et rapport photo.", "cta": "En savoir plus", "url": "https://aonosekehouseinvestmentdrc.site/services?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-qualite", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/qualite-banner.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Contrôle Qualité (banner)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Paiement Sécurisé 60/40 (preroll)', 'preroll', '{"title": "Ne payez le solde qu''à réception", "subtitle": "60 % sur compte séquestre, 40 % à la livraison conforme.", "cta": "Comment ça marche", "url": "https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-securise", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/securise-preroll.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Paiement Sécurisé 60/40 (preroll)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Paiement Sécurisé 60/40 (banner)', 'banner', '{"title": "Ne payez le solde qu''à réception", "subtitle": "60 % sur compte séquestre, 40 % à la livraison conforme.", "cta": "Comment ça marche", "url": "https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-securise", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/securise-banner.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Paiement Sécurisé 60/40 (banner)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Financement Trade (preroll)', 'preroll', '{"title": "Financez vos achats à l’international", "subtitle": "Préfinancement, crédit documentaire, assurance-crédit.", "cta": "Nous contacter", "url": "https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-financement", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/financement-preroll.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Financement Trade (preroll)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Financement Trade (banner)', 'banner', '{"title": "Financez vos achats à l’international", "subtitle": "Préfinancement, crédit documentaire, assurance-crédit.", "cta": "Nous contacter", "url": "https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-financement", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/financement-banner.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Financement Trade (banner)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Conseil & Accompagnement (preroll)', 'preroll', '{"title": "Un dossier d’import solide", "subtitle": "Étude de faisabilité, fiscalité et douane.", "cta": "Parler à un conseiller", "url": "https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-conseil", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/conseil-preroll.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Conseil & Accompagnement (preroll)');
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Conseil & Accompagnement (banner)', 'banner', '{"title": "Un dossier d’import solide", "subtitle": "Étude de faisabilité, fiscalité et douane.", "cta": "Parler à un conseiller", "url": "https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-conseil", "image": "https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/conseil-banner.jpg", "legal": "A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788", "variant": "souverain"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Conseil & Accompagnement (banner)');
end $$;

-- Vérification : doit afficher 16 lignes
select c.name, c.type, c.status from public.campaigns c join public.advertisers a on a.id = c.advertiser_id where a.name = 'Alpha Import Exchange' order by c.name;
