-- Campagnes Alpha Import Exchange : 14 secteurs (8 services + 6 catégories de produits) x pré-roll + bannière.
-- À exécuter dans Supabase → SQL Editor, APRÈS avoir téléversé les images (public/ads/sectors/*.jpg) dans le bucket public `ad-media`, dossier `sectors/`.
-- Idempotent : relancer le script ne crée pas de doublons et met à jour le contenu des campagnes existantes. Fichier généré par scripts/generate-ad-feeds.mjs.

do $$
declare adv uuid;
begin
  select id into adv from public.advertisers where name = 'Alpha Import Exchange' limit 1;
  if adv is null then
    insert into public.advertisers (name, contact_name, contact_email, phone, status, notes)
    values ('Alpha Import Exchange', 'A.Onoseke House Investment RDC', 'contact@aonosekehouseinvestmentdrc.site', '+243 999 894 788', 'active',
            'Annonceur maison : importation sécurisée Chine, Turquie, Dubaï, Japon, Thaïlande vers la RDC')
    returning id into adv;
  end if;

  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Sourcing & Achats (preroll)', 'preroll', '{"title":"Achetez directement à la source","subtitle":"Fournisseurs vérifiés en Chine, Turquie, Dubaï, Japon et Thaïlande.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-sourcing","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/sourcing-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/sourcing-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Sourcing & Achats (preroll)');
  update public.campaigns set content = '{"title":"Achetez directement à la source","subtitle":"Fournisseurs vérifiés en Chine, Turquie, Dubaï, Japon et Thaïlande.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-sourcing","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/sourcing-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/sourcing-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Sourcing & Achats (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Sourcing & Achats (banner)', 'banner', '{"title":"Achetez directement à la source","subtitle":"Fournisseurs vérifiés en Chine, Turquie, Dubaï, Japon et Thaïlande.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-sourcing","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/sourcing-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Sourcing & Achats (banner)');
  update public.campaigns set content = '{"title":"Achetez directement à la source","subtitle":"Fournisseurs vérifiés en Chine, Turquie, Dubaï, Japon et Thaïlande.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-sourcing","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/sourcing-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Sourcing & Achats (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Fret Maritime (preroll)', 'preroll', '{"title":"Vos conteneurs, de l''Asie à Kinshasa","subtitle":"Un suivi complet, de l''embarquement à la livraison.","cta":"Voir le circuit","url":"https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-maritime","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/maritime-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/maritime-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Fret Maritime (preroll)');
  update public.campaigns set content = '{"title":"Vos conteneurs, de l''Asie à Kinshasa","subtitle":"Un suivi complet, de l''embarquement à la livraison.","cta":"Voir le circuit","url":"https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-maritime","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/maritime-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/maritime-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Fret Maritime (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Fret Maritime (banner)', 'banner', '{"title":"Vos conteneurs, de l''Asie à Kinshasa","subtitle":"Un suivi complet, de l''embarquement à la livraison.","cta":"Voir le circuit","url":"https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-maritime","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/maritime-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Fret Maritime (banner)');
  update public.campaigns set content = '{"title":"Vos conteneurs, de l''Asie à Kinshasa","subtitle":"Un suivi complet, de l''embarquement à la livraison.","cta":"Voir le circuit","url":"https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-maritime","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/maritime-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Fret Maritime (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Fret Aérien (preroll)', 'preroll', '{"title":"Urgent ? Livré par avion","subtitle":"Des délais maîtrisés pour vos marchandises sensibles.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-aerien","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/aerien-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/aerien-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Fret Aérien (preroll)');
  update public.campaigns set content = '{"title":"Urgent ? Livré par avion","subtitle":"Des délais maîtrisés pour vos marchandises sensibles.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-aerien","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/aerien-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/aerien-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Fret Aérien (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Fret Aérien (banner)', 'banner', '{"title":"Urgent ? Livré par avion","subtitle":"Des délais maîtrisés pour vos marchandises sensibles.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-aerien","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/aerien-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Fret Aérien (banner)');
  update public.campaigns set content = '{"title":"Urgent ? Livré par avion","subtitle":"Des délais maîtrisés pour vos marchandises sensibles.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-aerien","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/aerien-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Fret Aérien (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Dédouanement Kinshasa (preroll)', 'preroll', '{"title":"La douane sans casse-tête","subtitle":"Commissionnaires agréés, dossier complet, circuit maîtrisé.","cta":"Comment ça marche","url":"https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-douane","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/douane-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/douane-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Dédouanement Kinshasa (preroll)');
  update public.campaigns set content = '{"title":"La douane sans casse-tête","subtitle":"Commissionnaires agréés, dossier complet, circuit maîtrisé.","cta":"Comment ça marche","url":"https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-douane","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/douane-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/douane-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Dédouanement Kinshasa (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Dédouanement Kinshasa (banner)', 'banner', '{"title":"La douane sans casse-tête","subtitle":"Commissionnaires agréés, dossier complet, circuit maîtrisé.","cta":"Comment ça marche","url":"https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-douane","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/douane-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Dédouanement Kinshasa (banner)');
  update public.campaigns set content = '{"title":"La douane sans casse-tête","subtitle":"Commissionnaires agréés, dossier complet, circuit maîtrisé.","cta":"Comment ça marche","url":"https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-douane","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/douane-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Dédouanement Kinshasa (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Contrôle Qualité (preroll)', 'preroll', '{"title":"Vérifié avant de partir","subtitle":"Inspection avant expédition et rapport photo.","cta":"En savoir plus","url":"https://aonosekehouseinvestmentdrc.site/services?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-qualite","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/qualite-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/qualite-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Contrôle Qualité (preroll)');
  update public.campaigns set content = '{"title":"Vérifié avant de partir","subtitle":"Inspection avant expédition et rapport photo.","cta":"En savoir plus","url":"https://aonosekehouseinvestmentdrc.site/services?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-qualite","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/qualite-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/qualite-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Contrôle Qualité (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Contrôle Qualité (banner)', 'banner', '{"title":"Vérifié avant de partir","subtitle":"Inspection avant expédition et rapport photo.","cta":"En savoir plus","url":"https://aonosekehouseinvestmentdrc.site/services?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-qualite","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/qualite-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Contrôle Qualité (banner)');
  update public.campaigns set content = '{"title":"Vérifié avant de partir","subtitle":"Inspection avant expédition et rapport photo.","cta":"En savoir plus","url":"https://aonosekehouseinvestmentdrc.site/services?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-qualite","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/qualite-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Contrôle Qualité (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Paiement Sécurisé 60/40 (preroll)', 'preroll', '{"title":"Ne payez le solde qu''à réception","subtitle":"60 % sur compte séquestre, 40 % à la livraison conforme.","cta":"Comment ça marche","url":"https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-securise","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/securise-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/securise-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Paiement Sécurisé 60/40 (preroll)');
  update public.campaigns set content = '{"title":"Ne payez le solde qu''à réception","subtitle":"60 % sur compte séquestre, 40 % à la livraison conforme.","cta":"Comment ça marche","url":"https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-securise","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/securise-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/securise-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Paiement Sécurisé 60/40 (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Paiement Sécurisé 60/40 (banner)', 'banner', '{"title":"Ne payez le solde qu''à réception","subtitle":"60 % sur compte séquestre, 40 % à la livraison conforme.","cta":"Comment ça marche","url":"https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-securise","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/securise-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Paiement Sécurisé 60/40 (banner)');
  update public.campaigns set content = '{"title":"Ne payez le solde qu''à réception","subtitle":"60 % sur compte séquestre, 40 % à la livraison conforme.","cta":"Comment ça marche","url":"https://aonosekehouseinvestmentdrc.site/how-it-works?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-securise","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/securise-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Paiement Sécurisé 60/40 (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Financement Trade (preroll)', 'preroll', '{"title":"Financez vos achats à l’international","subtitle":"Préfinancement, crédit documentaire, assurance-crédit.","cta":"Nous contacter","url":"https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-financement","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/financement-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/financement-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Financement Trade (preroll)');
  update public.campaigns set content = '{"title":"Financez vos achats à l’international","subtitle":"Préfinancement, crédit documentaire, assurance-crédit.","cta":"Nous contacter","url":"https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-financement","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/financement-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/financement-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Financement Trade (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Financement Trade (banner)', 'banner', '{"title":"Financez vos achats à l’international","subtitle":"Préfinancement, crédit documentaire, assurance-crédit.","cta":"Nous contacter","url":"https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-financement","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/financement-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Financement Trade (banner)');
  update public.campaigns set content = '{"title":"Financez vos achats à l’international","subtitle":"Préfinancement, crédit documentaire, assurance-crédit.","cta":"Nous contacter","url":"https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-financement","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/financement-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Financement Trade (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Conseil & Accompagnement (preroll)', 'preroll', '{"title":"Un dossier d’import solide","subtitle":"Étude de faisabilité, fiscalité et douane.","cta":"Parler à un conseiller","url":"https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-conseil","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/conseil-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/conseil-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Conseil & Accompagnement (preroll)');
  update public.campaigns set content = '{"title":"Un dossier d’import solide","subtitle":"Étude de faisabilité, fiscalité et douane.","cta":"Parler à un conseiller","url":"https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-conseil","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/conseil-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/conseil-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Conseil & Accompagnement (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Conseil & Accompagnement (banner)', 'banner', '{"title":"Un dossier d’import solide","subtitle":"Étude de faisabilité, fiscalité et douane.","cta":"Parler à un conseiller","url":"https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-conseil","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/conseil-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Conseil & Accompagnement (banner)');
  update public.campaigns set content = '{"title":"Un dossier d’import solide","subtitle":"Étude de faisabilité, fiscalité et douane.","cta":"Parler à un conseiller","url":"https://aonosekehouseinvestmentdrc.site/contact?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-conseil","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/conseil-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Conseil & Accompagnement (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Import · Électronique (preroll)', 'preroll', '{"title":"TV, téléphones, électroménager","subtitle":"Achetés à la source, contrôlés avant expédition, livrés à Kinshasa.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-electronique","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/electronique-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/electronique-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Import · Électronique (preroll)');
  update public.campaigns set content = '{"title":"TV, téléphones, électroménager","subtitle":"Achetés à la source, contrôlés avant expédition, livrés à Kinshasa.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-electronique","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/electronique-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/electronique-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Import · Électronique (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Import · Électronique (banner)', 'banner', '{"title":"TV, téléphones, électroménager","subtitle":"Achetés à la source, contrôlés avant expédition, livrés à Kinshasa.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-electronique","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/electronique-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Import · Électronique (banner)');
  update public.campaigns set content = '{"title":"TV, téléphones, électroménager","subtitle":"Achetés à la source, contrôlés avant expédition, livrés à Kinshasa.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-electronique","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/electronique-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Import · Électronique (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Import · Matériaux De Construction (preroll)', 'preroll', '{"title":"Équipez vos chantiers","subtitle":"Carrelage, sanitaires, quincaillerie : du sourcing à la livraison.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-btp","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/btp-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/btp-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Import · Matériaux De Construction (preroll)');
  update public.campaigns set content = '{"title":"Équipez vos chantiers","subtitle":"Carrelage, sanitaires, quincaillerie : du sourcing à la livraison.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-btp","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/btp-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/btp-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Import · Matériaux De Construction (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Import · Matériaux De Construction (banner)', 'banner', '{"title":"Équipez vos chantiers","subtitle":"Carrelage, sanitaires, quincaillerie : du sourcing à la livraison.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-btp","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/btp-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Import · Matériaux De Construction (banner)');
  update public.campaigns set content = '{"title":"Équipez vos chantiers","subtitle":"Carrelage, sanitaires, quincaillerie : du sourcing à la livraison.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-btp","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/btp-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Import · Matériaux De Construction (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Import · Pièces Auto & Motos (preroll)', 'preroll', '{"title":"Des pièces fiables, sans surprise","subtitle":"Contrôle avant expédition et suivi jusqu’à Kinshasa.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-auto","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/auto-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/auto-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Import · Pièces Auto & Motos (preroll)');
  update public.campaigns set content = '{"title":"Des pièces fiables, sans surprise","subtitle":"Contrôle avant expédition et suivi jusqu’à Kinshasa.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-auto","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/auto-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/auto-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Import · Pièces Auto & Motos (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Import · Pièces Auto & Motos (banner)', 'banner', '{"title":"Des pièces fiables, sans surprise","subtitle":"Contrôle avant expédition et suivi jusqu’à Kinshasa.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-auto","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/auto-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Import · Pièces Auto & Motos (banner)');
  update public.campaigns set content = '{"title":"Des pièces fiables, sans surprise","subtitle":"Contrôle avant expédition et suivi jusqu’à Kinshasa.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-auto","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/auto-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Import · Pièces Auto & Motos (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Import · Textile & Mode (preroll)', 'preroll', '{"title":"Habillez votre boutique","subtitle":"Tissus, vêtements, accessoires : sourcing en Chine, Turquie et Thaïlande.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-textile","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/textile-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/textile-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Import · Textile & Mode (preroll)');
  update public.campaigns set content = '{"title":"Habillez votre boutique","subtitle":"Tissus, vêtements, accessoires : sourcing en Chine, Turquie et Thaïlande.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-textile","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/textile-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/textile-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Import · Textile & Mode (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Import · Textile & Mode (banner)', 'banner', '{"title":"Habillez votre boutique","subtitle":"Tissus, vêtements, accessoires : sourcing en Chine, Turquie et Thaïlande.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-textile","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/textile-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Import · Textile & Mode (banner)');
  update public.campaigns set content = '{"title":"Habillez votre boutique","subtitle":"Tissus, vêtements, accessoires : sourcing en Chine, Turquie et Thaïlande.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-textile","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/textile-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Import · Textile & Mode (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Import · Énergie Solaire (preroll)', 'preroll', '{"title":"L’énergie qui ne s’arrête pas","subtitle":"Panneaux, onduleurs, batteries : importés avec contrôle qualité.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-solaire","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/solaire-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/solaire-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Import · Énergie Solaire (preroll)');
  update public.campaigns set content = '{"title":"L’énergie qui ne s’arrête pas","subtitle":"Panneaux, onduleurs, batteries : importés avec contrôle qualité.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-solaire","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/solaire-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/solaire-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Import · Énergie Solaire (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Import · Énergie Solaire (banner)', 'banner', '{"title":"L’énergie qui ne s’arrête pas","subtitle":"Panneaux, onduleurs, batteries : importés avec contrôle qualité.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-solaire","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/solaire-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Import · Énergie Solaire (banner)');
  update public.campaigns set content = '{"title":"L’énergie qui ne s’arrête pas","subtitle":"Panneaux, onduleurs, batteries : importés avec contrôle qualité.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-solaire","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/solaire-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Import · Énergie Solaire (banner)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Import · Machines & Équipements (preroll)', 'preroll', '{"title":"Équipez votre activité","subtitle":"Machines, outils et équipements : du sourcing au dédouanement.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-machines","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/machines-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/machines-portrait.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Import · Machines & Équipements (preroll)');
  update public.campaigns set content = '{"title":"Équipez votre activité","subtitle":"Machines, outils et équipements : du sourcing au dédouanement.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=preroll&utm_campaign=alpha-import-2026&utm_content=sector-machines","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/machines-preroll.jpg","imagePortrait":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/machines-portrait.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Import · Machines & Équipements (preroll)';
  insert into public.campaigns (advertiser_id, name, type, content, status, weight)
  select adv, 'Alpha Import — Import · Machines & Équipements (banner)', 'banner', '{"title":"Équipez votre activité","subtitle":"Machines, outils et équipements : du sourcing au dédouanement.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-machines","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/machines-banner.jpg"}'::jsonb, 'active', 10
  where not exists (select 1 from public.campaigns where advertiser_id = adv and name = 'Alpha Import — Import · Machines & Équipements (banner)');
  update public.campaigns set content = '{"title":"Équipez votre activité","subtitle":"Machines, outils et équipements : du sourcing au dédouanement.","cta":"Demander un devis","url":"https://aonosekehouseinvestmentdrc.site/register?utm_source=iptv-player&utm_medium=banner&utm_campaign=alpha-import-2026&utm_content=sector-machines","legal":"A.Onoseke House Investment RDC · RCCM CD/KNM/RCCM/21-A-01949 · Siège : Av. Haut Congo n°13, Ngaliema, Kinshasa · contact@aonosekehouseinvestmentdrc.site · +243 999 894 788","variant":"souverain","image":"https://cvuhvppsdzrjtvrtvrlv.supabase.co/storage/v1/object/public/ad-media/sectors/machines-banner.jpg"}'::jsonb, updated_at = now() where advertiser_id = adv and name = 'Alpha Import — Import · Machines & Équipements (banner)';
end $$;

-- Vérification : doit afficher 28 lignes
select c.name, c.type, c.status from public.campaigns c join public.advertisers a on a.id = c.advertiser_id where a.name = 'Alpha Import Exchange' order by c.name;
